### ISSUE TITLE
关于 `injected-script`和 `content-script` 的描述有误。

### ISSUE THREAD

**Issue by hiyangguo** [sxei/chrome-plugin-demo#10]
亲自试验了一下，在 chrome 70 中， 直接使用在 `mainfest.json` 中配置的 content-script 是可以给 dom 绑定事件的。不知道是不是文章有问题。 

> content-scripts和原始页面共享DOM，但是不共享JS，如要访问页面JS（例如某个JS变量），只能通过injected js来实现。

这句话的意思是注入的 script 可以访问页面js 中的变量？官方文档说的是，content-scirpt 是隔离运行的，所以不能访问吧？能提供一下demo 么？ 感谢。

**Comment by sxei** [comment]
这句话没有说错啊，injected js 和 content-script不是一个东西，injected js指的是通过类似document.body.appendChild 这种手段注入的jS，这种JS和普通JS没有任何差别，是可以访问原始JS的，相反， content-script不能访问原始js
