### ISSUE TITLE
请教一个问题,可否在content-script中改变window下变量的值

### ISSUE THREAD

**Issue by liuyibo123** [sxei/chrome-plugin-demo#12]
比如当前页面有一个<code>window.tracing</code>变量为`false`，可否通过某种方式改变为`window.tracing = true`
谢谢！

**Comment by liuyibo123** [comment]
或者content-script能否正向传递消息到inject

**Comment by sxei** [comment]
可以的，但是不能直接修改，需要通过postMessage间接去修改。
