### ISSUE TITLE
inject注入js加载顺序问题

### ISSUE THREAD

**Issue by zxcvbnm3057** [sxei/chrome-plugin-demo#17]
如果在inject注入的js中需要调用jq，执行
injectCustomJs("js/jquery-3.1.1.min.js");
injectCustomJs();
然而仍报错 Uncaught ReferenceError: $ is not defined
调试发现jq确实在inject.js之前注入，但执行顺序似乎有问题，请问该如何解决呢

**Comment by lujq** [comment]
> 如果在inject注入的js中需要调用jq，执行
> injectCustomJs("js/jquery-3.1.1.min.js");
> injectCustomJs();
> 然而仍报错 Uncaught ReferenceError: $ is not defined
> 调试发现jq确实在inject.js之前注入，但执行顺序似乎有问题，请问该如何解决呢

manifest.json中 "web_accessible_resources": 是否有引用jQuery文件？这里也需要申明引入该文件。
祝好！

**Comment by zxcvbnm3057** [comment]
> > 如果在inject注入的js中需要调用jq，执行
> > injectCustomJs("js/jquery-3.1.1.min.js");
> > injectCustomJs();
> > 然而仍报错 Uncaught ReferenceError: $ is not defined
> > 调试发现jq确实在inject.js之前注入，但执行顺序似乎有问题，请问该如何解决呢
> 
> manifest.json中 "web_accessible_resources": 是否有引用jQuery文件？这里也需要申明引入该文件。
> 祝好！

谢谢，已经引入了，console也能看见加载成功，但是似乎在inject.js执行后引入的，导致inject.js无法使用jq语句，<script>标签插入顺序也没有错

**Comment by lujq** [comment]
> > > 如果在inject注入的js中需要调用jq，执行
> > > injectCustomJs("js/jquery-3.1.1.min.js");
> > > injectCustomJs();
> > > 然而仍报错 Uncaught ReferenceError: $ is not defined
> > > 调试发现jq确实在inject.js之前注入，但执行顺序似乎有问题，请问该如何解决呢
> > 
> > 
> > manifest.json中 "web_accessible_resources": 是否有引用jQuery文件？这里也需要申明引入该文件。
> > 祝好！
> 
> 谢谢，已经引入了，console也能看见加载成功，但是似乎在inject.js执行后引入的，导致inject.js无法使用jq语句，<script>标签插入顺序也没有错

我好像也遇到过这样的问题，你试试在manifest.json中，content_scripts中也引入下。
"content_scripts": [
    {
      "matches": [
        "<all_urls>"
      ],
      "js": [
        "js/jquery-3.3.1.min.js",
        "js/content-script.js"
      ],
      "css": [
        "css/custom.css"
      ],
      "run_at": "document_start"
    }
  ],

chrome plugin的js引用域我一直有点疑惑，希望能帮助到你。

**Comment by zxcvbnm3057** [comment]
> > > > 如果在inject注入的js中需要调用jq，执行
> > > > injectCustomJs("js/jquery-3.1.1.min.js");
> > > > injectCustomJs();
> > > > 然而仍报错 Uncaught ReferenceError: $ is not defined
> > > > 调试发现jq确实在inject.js之前注入，但执行顺序似乎有问题，请问该如何解决呢
> > > 
> > > 
> > > manifest.json中 "web_accessible_resources": 是否有引用jQuery文件？这里也需要申明引入该文件。
> > > 祝好！
> > 
> > 
> > 谢谢，已经引入了，console也能看见加载成功，但是似乎在inject.js执行后引入的，导致inject.js无法使用jq语句，<script>标签插入顺序也没有错
> 
> 我好像也遇到过这样的问题，你试试在manifest.json中，content_scripts中也引入下。
> "content_scripts": [
> {
> "matches": [
> "<all_urls>"
> ],
> "js": [
> "js/jquery-3.3.1.min.js",
> "js/content-script.js"
> ],
> "css": [
> "css/custom.css"
> ],
> "run_at": "document_start"
> }
> ],
> 
> chrome plugin的js引用域我一直有点疑惑，希望能帮助到你。

谢谢，不过我还是没有解决，我已经全部使用原生js语句了
