### ISSUE TITLE
 "content_scripts" 里用 JS 引入外部 CSS 文件的样式加载问题

### ISSUE THREAD

**Issue by Pudge1996** [sxei/chrome-plugin-demo#19]
我在 Stylus 里给一个网站写好了样式，想做成一个插件。 
我在 manifest.json 中引入了一段 JS, JS里也引入了一个外部 CSS 文件。

// manifest.json 
 "content_scripts": [{
          ...
          "js": ["js/custom.js"],
          "run_at": "document_start"
      }],

// JS
var style = document.createElement('link');
style.rel = 'stylesheet';
style.type = 'text/css';
style.href = chrome.extension.getURL('css/custom.css');
(document.head||document.documentElement).appendChild(style);

现在的情况是如果 run_at 设置为 “start”，样式会直接加载在 <head> 的前面，我的样式会被下面源网站的 CSS 文件所覆盖（我写的 CSS 优先级较低），如果  run_at  设置为 “idle” 或 “end”，网页会先显示原本的 CSS，再显示我写的 CSS，画面会跳一下。

请问有什么方法可以让网站先看到我写的 CSS，而不被源网站的覆盖掉吗？（除了用 # 或 !important 改优先级，因为行数还挺多的，当时在 stylus 里改的时候没想到）

**Comment by sxei** [comment]
我建议还是通过增加CSS优先级来解决，行数很多的话用less或sass编译一下就好了，或者自己写几行代码批处理一下。
实在不行，只能让页面先强行隐藏，比如body: {display:none}，等你自己的css加载完毕再回恢复。
