### ISSUE TITLE
popup的窗口 如何使用圆角

### ISSUE THREAD

**Issue by hahaxo** [sxei/chrome-plugin-demo#5]
例如这个插件：
https://chrome.google.com/webstore/detail/visual-inspector-by-canva/efaejpgmekdkcngpbghnpcmbpbngoclc

**Comment by sxei** [comment]
看了一下你说的这个插件，它的popup是假的，其实是往页面注入了一个iframe。

**Comment by sxei** [comment]
关于圆角以及边缘部分的背景色目前我也没找到设置方法。但是楼上给出的这个插件确实给出了另外一种思路。
