### ISSUE TITLE
大佬,问个问题

### ISSUE THREAD

**Issue by Lidihua** [sxei/chrome-plugin-demo#8]
我有个需求,假如我在某一个页面上看到一些感兴趣的字眼,比如机器学习,我想做一个插件,就是可以通过选定 机器学习 这四个字,右击,然后出现"在网站A上搜索 机器学习 ",这样.
但这个网站A啊,它不是像百度,豆瓣那样可以通过构造url然后通过get的形式达到目的,而是以关键字作为key,POST一个search的url,请问这种要怎么做啊?

**Comment by sxei** [comment]
还是和普通方式一样，打开一个新的页面，传一个参数，当打开对应新页面时，注入content-script，如果发现地址包含某个参数就发起post请求。
